# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comentario',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
